# Generated by Django 4.0.5 on 2022-07-05 06:48

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the project.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('Up Coming', 'Up Coming'), ('Under development', 'Under development'), ('Archived', 'Archived')], help_text='Select the status of the project.', max_length=32)),
                ('about', models.CharField(help_text='Write a short description of the project.', max_length=512)),
                ('url', models.URLField(default='https://github.com/youzarsiph/', help_text='Enter the repository or website url of the project.')),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the project.', null=True, upload_to='images/projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(portfolio.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the course provider.', max_length=64, unique=True)),
                ('url', models.URLField(help_text='Enter the website url of the provider.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(portfolio.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the skill.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(portfolio.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the tag.', max_length=128, unique=True)),
                ('color', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('info', 'Cyan'), ('danger', 'Red'), ('warning', 'Yellow')], help_text='Select the color of the tag.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(portfolio.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the certificate.', max_length=128, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Leave empty if no expiration date.', null=True)),
                ('credential', models.URLField(default='https://coursera.org/verify/', help_text='Enter the verification url of the certificate.')),
                ('credential_id', models.CharField(help_text='Enter the credential id.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Select the course provider', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.provider')),
                ('tag', models.ForeignKey(blank=True, help_text='Select the learning product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.tag')),
            ],
            bases=(portfolio.models.BaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the badge.', max_length=64, unique=True)),
                ('url', models.URLField(default='https://credly.com/', help_text='Enter the verification url of the badge.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, help_text='Select provider of the badge.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.provider', verbose_name='Issued by')),
            ],
            bases=(portfolio.models.BaseModel, models.Model),
        ),
    ]
