# Generated by Django 4.0.5 on 2022-08-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Enter the url of the project demo.', null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(help_text='Enter the name of the badge. (Required)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='url',
            field=models.URLField(default='https://credly.com/', help_text='Enter the verification url of the badge. (Required)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential',
            field=models.URLField(default='https://coursera.org/verify/', help_text='Enter the verification url of the certificate. (Required)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(help_text='Enter the credential id. (Required)', max_length=10),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(help_text='Enter the name of the certificate. (Required)', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='Your message. (Required)', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(help_text='Your email address. (Required)', max_length=256),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(help_text='Your full name. (Required)', max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.CharField(help_text='Write a short description of the project. (Required)', max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Enter the name of the project. (Required)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Archived', 'Archived'), ('Up Coming', 'Up Coming'), ('Under development', 'Under development')], help_text='Select the status of the project. (Required)', max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(default='https://github.com/youzarsiph/', help_text='Enter the repository url. (Required)'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Enter the name of the course provider. (Required)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='url',
            field=models.URLField(help_text='Enter the website url of the provider. (Required)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Enter the name of the skill. (Required)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('info', 'Cyan'), ('danger', 'Red'), ('warning', 'Yellow')], help_text='Select the color of the tag. (Required)', max_length=16),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Enter the name of the tag. (Required)', max_length=128, unique=True),
        ),
    ]
